name: exposome
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - numpy
  - geopandas
  - shapely
  - pyproj
  - osmnx
  - folium
  - matplotlib
  - requests
  - scipy
  - scikit-image
  - opencv
  - openpyxl
  - jupyterlab
  - ipykernel
  - nbformat
  - nbconvert
  - pyyaml
  - typer
  - rasterio
  - rioxarray
  - xarray-spatial
  - rasterstats
  - pip
  - pip:
      - earthengine-api
      - geemap
      - openaq
      - segment-geospatial
      - rarfile
