schema_version: 1
id: air_quality
settings:
  year: 2024
  start_date: '2024-01-01'
  end_date: '2024-12-31'
  collections:
    no2:
      id: COPERNICUS/S5P/OFFL/L3_NO2
      band: tropospheric_NO2_column_number_density
      scale_meters: 1113
      multiplier: 1.0e15
    o3:
      id: COPERNICUS/S5P/OFFL/L3_O3
      band: O3_column_number_density
      scale_meters: 7000
      multiplier: 1.0e15
    aod:
      id: MODIS/061/MCD19A2_GRANULES
      band: Optical_Depth_047
      scale_meters: 3000
      qa_band: AOD_QA
      qa_mask_max: 1
      scale_factor: 0.001
    angstrom:
      id: MODIS/061/MCD19A2_GRANULES
      fine_mode_band: FineModeFraction
      scale_meters: 3000
      qa_band: AOD_QA
      qa_mask_max: 1
      scale_factor: 0.001
  who_guidelines:
    pm25: 5.0
    no2: 10.0
